apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
  namespace: linkerd
spec:
  interval: 60m
  url: https://flagger.app

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: linkerd
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 60m0s
  values:
    crd.create: false
    meshProvider: linkerd
    metricsServer: http://prometheus.linkerd-viz:9090