version: 2.1
jobs:
  plan-tf-ci:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            apk add make
            make plan-infra
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply-tf-ci:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - run:
          name: terraform apply
          command: |
            apk add make
            make apply-infra

workflows:
  Example-Workflow:
    jobs:
      - plan-tf-ci:
          filters:
              branches:
                only:
                  - master
      - apply-tf-ci:
          type: approval
          requires:
            - plan-tf-ci
          filters:
              branches:
                only:
                  - master