version: 2.1
jobs:
  plan-tf-ci:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            apk add make
            make plan-infra

  apply-tf-ci:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform apply
          command: |
            apk add make
            make apply-infra
  
  test-service:
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - run:
          name: kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - run:
          name: terratest
          command: |
            make terratest
workflows:
  terraform-deploy:
    jobs:
      - plan-tf-ci:
          filters:
              branches:
                only:
                  - master
      - hold-apply:
          type: approval
          requires:
            - plan-tf-ci
      - apply-tf-ci:
          filters:
              branches:
                only:
                  - master
          requires:
            - hold-apply
      - test-service:
          filters:
              branches:
                only:
                  - master
          requires:
            - apply-tf-ci