version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.0.1
jobs:
  install-flux:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run:
          name: fluxctl
          command: |
            curl -s https://fluxcd.io/install.sh | sudo bash
      - run:
          name: kubeconfig
          command: |
            mkdir ~/.kube
            chmod +x scripts/kubeconfig.sh
            bash scripts/kubeconfig.sh
      - run:
          name: bootstrap-flux
          command: |
            flux bootstrap github --owner=ui1diegocristobal --repository=TFGpoc --path=app --branch=master --personal

workflows:
  flows:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: .circleci/terraform-cicd.yml
          mapping: |
            infra/.*
      - install-flux:
          filters:
            tags:
              only: /^flux-.*/
            branches:
              ignore: /.*/