apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webapp-staging
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/staging/webapp
      version: 2.1.3
      sourceRef:
        kind: GitRepository
        name: webapp-staging
        namespace: staging
      interval: 1m
  values:
    replicaCount: 1