apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: webapp-staging
  namespace: staging
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
    namespace: flux-system
  url: ssh://git@github.com/ui1diegocristobal/TFGpoc
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/staging/webapp/    