apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 60m
  url: https://helm.linkerd.io/stable

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd2
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
  interval: 60m0s
  values:
    identityTrustAnchorsPEM: ca.crt
    identity.issuer.tls.crtPEM: issuer.crt
    identity.issuer.tls.keyPEM: issuer.key
    identity.issuer.crtExpiry: "2023-06-10T20:42:55Z"