apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webapp-prod
  namespace: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/prod/webapp
      version: 0.1.8
      sourceRef:
        kind: GitRepository
        name: webapp-prod
        namespace: prod
      interval: 1m
  values:
    replicaCount: 2
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80