apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: webapp-prod
  namespace: prod
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/ui1diegocristobal/TFGpoc
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts