apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: webapp-prod
  namespace: prod
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/ui1diegocristobal/TFGpoc/charts/prod
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/webapp/    